#!/bin/bash

## Autostart
pgrep -x sxhkd > /dev/null || sxhkd -r ~/.sxhkd.log &
picom &
#feh --bg-fill ~/Images/Wallpaper/wallpaper.jpg &
feh --bg-fill ~/Images/Wallpaper/pxfuel.jpg &
sh ~/.config/polybar/launch.sh &

SCREENLAYOUT=$(autorandr --detected 2>/dev/null)

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR_1="HDMI-1"
EXTERNAL_MONITOR_2="DP-3"


case $SCREENLAYOUT in
	"triple_work")
		triple_work()
		;;
	"double_work")
		double_work()
		;;
	"single")
		single()
		;;
	"triple_home")
		triple_home()
		;;
esac

triple_work() {
	SCREENNAMES=$(autorandr --fingerprint 2>/dev/null | awk '{print $1}')
	# lines are arbitrary
	INTERNAL_MONITOR=$(echo $SCREENNAMES | awk 'NR==3 {print}')
	EXTERNAL_MONITOR_1=$(echo $SCREENNAMES | awk 'NR==1 {print}')
	EXTERNAL_MONITOR_2=$(echo $SCREENNAMES | awk 'NR==2 {print}')

	bspc monitor "$EXTERNAL_MONITOR_2" -d 1 2 3 4
	bspc monitor "$EXTERNAL_MONITOR_1" -d 7 8 9 0
	bspc monitor "$INTERNAL_MONITOR" -d 5 6
}
double_work() {
	SCREENNAMES=$(autorandr --fingerprint 2>/dev/null | awk '{print $1}')
	# lines are arbitrary
	INTERNAL_MONITOR=$(echo $SCREENNAMES | awk 'NR==2 {print}')
	EXTERNAL_MONITOR_1=$(echo $SCREENNAMES | awk 'NR==1 {print}')

	bspc monitor "$EXTERNAL_MONITOR_1" -d 7 8 9 0
	bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4
}
single() {
	INTERNAL_MONITOR=$(autorandr --fingerprint 2>/dev/null | awk '{print $1}')
	bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 7 8 9 0
}
triple_home() {
	# todo : change it
	SCREENNAMES=$(autorandr --fingerprint 2>/dev/null | awk '{print $1}')
	# lines are arbitrary
	INTERNAL_MONITOR=$(echo $SCREENNAMES | awk 'NR==3 {print}')
	EXTERNAL_MONITOR_1=$(echo $SCREENNAMES | awk 'NR==1 {print}')
	EXTERNAL_MONITOR_2=$(echo $SCREENNAMES | awk 'NR==2 {print}')


	bspc monitor "$EXTERNAL_MONITOR_2" -d 1 2 3 4
	bspc monitor "$EXTERNAL_MONITOR_1" -d 7 8 9 0
	bspc monitor "$INTERNAL_MONITOR" -d 5 6

}

# BSPWM config
bspc config border_width		1
bspc config window_gap			0
bspc config active_border_color '#a470a4'
bspc config normal_border_color '#868fb0'
bspc config focused_border_color '#86aefd'
bspc config split_ratio			0.5

# BSPWM rules
bspc config external_rules_command ~/.config/bspwm/external_rules

bspc rule -a Alacritty desktop=^5 follow=on
bspc rule -a kitty desktop=^5 follow=on
bspc rule -a Google-chrome desktop=^6 follow=on
bspc rule -a Google-chrome-stable desktop=^6 follow=on
bspc rule -a firefox desktop=^6 follow=on
bspc rule -a Org.gnome.Nautilus desktop=^7 follow=on
bspc rule -a Spotify desktop=^1 
bspc rule -a discord desktop=^2 follow=on
bspc rule -a TelegramDesktop desktop=^2 follow=on

