import = [
	"~/.config/alacritty/custom-argonaut.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Monaco Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Monaco Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Monaco Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "R"
mods = "Control|Shift"

[window]
opacity = 1
